# Generated by Django 5.0.2 on 2024-03-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidgraph', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='first_name',
        ),
    ]
