# Generated by Django 4.1.4 on 2024-08-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidgraph', '0004_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='myvideo',
        ),
    ]
